coverage:
  status:
    project:
      default: off
      webui:
        flags: webui
flags:
  # filter the folder(s) you wish to measure by that flag
  webui:
    paths:
      - web-ui/

# disable PR comments
comment: false
