sudo: required

language: java

jdk:
  - oraclejdk8

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - nvm install 7.7 # web-ui

  # Codacy coverage
  - curl -sL http://repo1.maven.org/maven2/com/codacy/codacy-coverage-reporter/1.0.13/codacy-coverage-reporter-1.0.13-assembly.jar > ~/codacy-coverage-reporter.jar
  # / Codacy coverage

install: true

script:
  # Unit-test and build CLI tool
  - cd cli/
  - ./gradlew build --info
  - cd ..

  # Unit-test and build server
  - cd server/
  - ./gradlew build --info
  - cd ..

  # web-ui
  - nvm use 7.7
  - node --version
  - npm --version
  - cd web-ui/
  - npm install -q
  - npm test
  - npm run build
  - cd ..

  # Launch local zally server
  - cd server/
  - echo "spring.profiles.active=dev" > application.properties
  - ./gradlew bootRun > /dev/null &
  - echo $! > /tmp/zally_server.pid
  - cd ..

  # Wait until Spring Boot will start
  - while ! echo "GET / HTTP/1.0\n" | nc localhost 8080; do sleep 3; done

  # Run CLI integration test
  - ./cli/integration_tests/tests.bats

  # Kill Zally server instace
  - kill -9 `cat /tmp/zally_server.pid`

after_success:
  - java -cp ~/codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter --language Java --coverageReport cli/build/reports/jacoco/test/jacocoTestReport.xml -t $CODACY_PROJECT_TOKEN
  - java -cp ~/codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter --language Java --coverageReport server/build/reports/jacoco/test/jacocoTestReport.xml -t $CODACY_PROJECT_TOKEN
