dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq --allow-unauthenticated
  - sudo apt-get install -qq bats
  - eval "$(GIMME_GO_VERSION=1.8.3 gimme)"

  # Codacy coverage
  - curl -sL http://repo1.maven.org/maven2/com/codacy/codacy-coverage-reporter/1.0.13/codacy-coverage-reporter-1.0.13-assembly.jar > ~/codacy-coverage-reporter.jar
  # / Codacy coverage

install: true

script:
  # Unit-test and build CLI tool
  - cd cli/
  - ./gradlew build --info
  - cd ..

  # Unit-test and build server
  - cd server/
  - ./gradlew build --info
  - cd ..

  # Launch local zally server
  - cd server/
  - ./gradlew bootRun > /dev/null &
  - echo $! > /tmp/zally_server.pid
  - cd ..

  # Wait until Spring Boot will start
  - while ! echo "GET / HTTP/1.0\n" | nc localhost 8080; do sleep 3; done

  # Run CLI integration test
  - ./cli/integration_tests/tests.bats

  # Unit-test and build Go version of CLI
  - export ZALLY_GO_PATH="$GOPATH/src/github.com/zalando-incubator/zally"
  - mkdir -p $ZALLY_GO_PATH
  - cp -R . $ZALLY_GO_PATH
  - cd $ZALLY_GO_PATH/cli-go/zally
  - go get -t
  - go test -v -cover ./...
  - go build
  - cd ../..

  # Run Go version of CLI integration test
  - ./cli-go/integration_tests/tests.bats
  - cd $TRAVIS_BUILD_DIR

  # Kill Zally server instace
  - kill -9 `cat /tmp/zally_server.pid`

  # Unit-test web UI
  - cd web-ui
  - node --version
  - npm --version
  - npm install -q
  - npm test
  - npm run build
  - npm run codecov
  - cd $TRAVIS_BUILD_DIR
  
after_success:
  - java -cp ~/codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter --language Java --coverageReport cli/build/reports/jacoco/test/jacocoTestReport.xml -t $CODACY_PROJECT_TOKEN
  - java -cp ~/codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter --language Java --coverageReport server/build/reports/jacoco/test/jacocoTestReport.xml -t $CODACY_PROJECT_TOKEN
