allow_concurrent_steps: true
version: "2017-09-20"
pipeline:
  - id: build-server
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/jdk17
    commands:
      - desc: Build server
        cmd: |
          cd $PWD/server
          ./gradlew --console=plain build
          if [ -n "${CDP_PULL_REQUEST_NUMBER}" ]; then
            echo "We're in a pull request, aborting."; exit 0;
          fi;
          PREFIX="pierone.stups.zalan.do/builder-knowledge"
          IMAGE="${PREFIX}/zally:${CDP_PULL_REQUEST_NUMBER}"
          docker build -t "${IMAGE}" . && docker push "${IMAGE}"
    cache:
      paths: [ ~/.gradle/caches, ~/.gradle/wrapper ]

  - id: web-ui
    type: script
    vm_config:
      type: linux
      image: cdp-runtime/nodejs-18
    commands:
      - desc: Build Web UI
        cmd: |
          cd $PWD/web-ui
          yarn install -q ; yarn test ; yarn build
          if [ -n "${CDP_PULL_REQUEST_NUMBER}" ]; then
            echo "We're in a pull request, aborting."; exit 0;
          fi;
          PREFIX="pierone.stups.zalan.do/builder-knowledge"
          IMAGE="${PREFIX}/zally-web-ui-dummy:${CDP_BUILD_VERSION}"
          docker build -t "${IMAGE}" . && docker push "${IMAGE}"
    cache:
      paths: [ ~/.npm ]
