spring:
  profiles:
    active: production
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  oauth2:
    resource:
      tokenInfoUri: "https://info.services.auth.zalando.com/oauth2/tokeninfo"

endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

security:
  basic:
    enabled: false

management.port: 7979

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

rules-config-path: "rules-config.conf"

# FYI: S001 is disabled because Zalando's API guidelines changed.
zally:
  ignoreRules: S001,S010
