endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

management:
  port: 0

security:
  basic:
    enabled: false

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

rules-config-path: "rules-config-test.conf"
