swagger: '2.0'
info:
 title: Zally
 description: Zalando's API Linter
 version: "0.0.1"
 contact:
   name: Felix Mueller
   email: felix.mueller2@zalando.de
host: "zally.architecture.zalan.do"
schemes:
  - https
basePath: /
securityDefinitions:
  oauth2:
    type: oauth2
    authorizationUrl: https://auth.zalando.com/oauth2/authorize
    flow: password
    scopes:
      uid: submit API specification for validation
parameters:
  Authorization:
    name: Authorization
    in: header
    description: OAUTH2 (IAM)
    required: true
    type: string
    format: OAUTH2 (IAM)
  LintingRequest:
    name: Request
    in: body
    description: Linting Request
    required: true
    schema:
      $ref: '#/definitions/LintingRequest'

paths:
  '/api-violations':
    post:
      summary:
        Retrieves list of API violations based on the uploaded swagger file
      description:
        Retrieves list of API violations based on the uploaded swagger file
      parameters:
        - $ref: '#/parameters/Authorization'
        - $ref: '#/parameters/LintingRequest'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: API swagger is OK
          schema:
            $ref: '#/definitions/LintingResponse'
        400:
          description: Input file not parsable
          schema:
            $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
        default:
          description: An array of error objects
          schema:
            $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
      security:
        - oauth2:
          - uid

definitions:
  LintingRequest:
    type: object
    description: Request containing a swagger definition file
    properties:
      api_defintion:
        type: object

  LintingResponse:
    type: object
    description: Linting Response
    required:
      - violations
    properties:
      violations:
        type: array
        items:
          $ref: '#/definitions/Violation'
      message:
        type: string

  Violation:
    type: object
    description: Violation Object
    required:
      - title
      - description
    properties:
      title:
        type: string
      description:
        type: string
      violation_type:
        type: string
        enum:
        - MUST
        - SHOULD
        - COULD
        - HINT
      rule_link:
        type: string
      paths:
        type: array
        items:
          type: string
