endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

security:
  basic:
    enabled: false

management.port: 0

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-github-api.yaml"

tokens:
  accessTokenUri: https://auth.example.com/oauth2/access_token?realm=testing
  credentialsDirectory: src/test/resources/credentials
  token-configuration-list:
    - tokenId: zally
      scopes:
        - uid

zally:
  apiUrl: http://localhost:9099

github:
  apiUrl: http://localhost:8088
  oauthToken: abcdef1234567890abcdef1234567890
  secret: abcdef1234567890abcdef1234567890