endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false


security:
  basic:
    enabled: false

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-github-api.yaml"

management.port: 8080
