endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

spring:
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

security:
  basic:
    enabled: false

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-github-api.yaml"

zally:
  apiUrl: http://localhost:8080

github:
  apiUrl: http://localhost:8088
  oauthToken: abcdef1234567890abcdef1234567890
  secret: abcdef1234567890abcdef1234567890

tokens:
  accessTokenUri: https://auth.example.com/oauth2/access_token?realm=testing
  token-configuration-list:
    - tokenId: zally
      scopes:
        - uid

server.port: 8081
management.port: 8081

bark:
  serverUrl: http://localhost:8081