spring:
  profiles:
    active: production
  oauth2:
    resource:
      tokenInfoUri: ${TOKEN_INFO_URI}

endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

security:
  basic:
    enabled: false

management.port: ${MANAGEMENT_PORT}

tokens:
  accessTokenUri: https://auth.example.com/oauth2/access_token?realm=testing
  token-configuration-list:
    - tokenId: zally
      scopes:
        - uid

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-github-api.yaml"

zally:
  apiUrl: http://localhost:9099

github:
  apiUrl: http://localhost:8088
  oauthToken: abcdef1234567890abcdef1234567890
  secret: abcdef1234567890abcdef1234567890

---
spring.profiles: local
TOKEN_INFO_URI: https://auth.example.com/oauth2/tokeninfo
MANAGEMENT_PORT: 7979
