endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

security:
  basic:
    enabled: false

management.port: 0

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-github-api.yaml"

zally:
  oauthToken: abcdef1234567890abcdef1234567890
  secret: abcdef1234567890abcdef1234567890


github:
  apiUrl: http://localhost:8088