endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false


security:
  basic:
    enabled: false

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-github-api.yaml"

zally:
  apiUrl: http://localhost:8080

github:
  apiUrl: http://localhost:8088
  oauthToken: abcdef1234567890abcdef1234567890
  secret: abcdef1234567890abcdef1234567890

server.port: 8081
management.port: 8081
