endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

security:
  basic:
    enabled: false

management.port: 0

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-github-api.yaml"
